from sqlalchemy import ARRAY, Boolean, Date
from sqlalchemy import Column, Integer, String ,Float,Text, DECIMAL,Time
from sqlalchemy.dialects.mysql import CHAR
from caerp_db.database import caerp_base
from sqlalchemy.orm import relationship
from sqlalchemy import ForeignKey
from datetime import date, datetime 
from sqlalchemy import Column, DateTime, func
from sqlalchemy import Enum

class gstTest(caerp_base):
    __tablename__ = 'gst_test'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(100), default=None)
    gst = Column(String(100), default=None)
    amount = Column(DECIMAL(15,2), default=None)


class gstr2b(caerp_base):
    __tablename__ = 'purchase_gstr2b'
    p_g_id = Column(Integer, primary_key=True, autoincrement=True)
    cfs = Column(String(5), default=None)
    type = Column(String(10), default=None)
    supplier_name = Column(String(200), default=None)
    supplier_tax_period= Column(Date, default=None)
    supplier_file_date= Column(Date, default=None)
    gstin  = Column(String(50), default=None)
    invoice_date= Column(Date, default=None)
    invoice_number = Column(String(40), default=None)
    applicable_tax_per = Column(DECIMAL(4,2), default=None)
    state = Column(Integer,default=0)
    reverse_charge = Column(String(5), default=None)
    taxable_rate = Column(DECIMAL(6,2), default=None)
    taxable_value = Column(DECIMAL(15,2), default=None)
    iamt = Column(DECIMAL(15,2), default=None)
    camt = Column(DECIMAL(15,2), default=None)
    samt = Column(DECIMAL(15,2), default=None)
    csamt = Column(DECIMAL(15,2), default=None)
    elg  = Column(String(10), default=None)
    tx_i = Column(DECIMAL(15,2), default=None)
    tx_c = Column(DECIMAL(15,2), default=None)
    tx_s = Column(DECIMAL(15,2), default=None)
    tx_cs = Column(DECIMAL(15,2), default=None)
    refund_number = Column(String(40), default=None)
    refund_date= Column(Date, default=None)
    reason = Column(Text, nullable=False)
    document_type = Column(String(5), default=None)
    p_gst = Column(String(5), default=None)
    chksum = Column(Text, nullable=False)
    flag = Column(String(5), default=None)
    cflag = Column(String(5), default=None)
    inv_typ = Column(String(5), default=None)
    new_entry = Column(Integer,default=0)
    gstr_description = Column(Text, nullable=False)
    amd_invoice_number = Column(String(30), default=None)
    amd_invoice_date= Column(Date, default=None)
    tax_period  = Column(DateTime, nullable=True)
    entry_date  = Column(DateTime, nullable=True)


class  gstr2a(caerp_base):
    __tablename__ = 'purchase_gstr'
    p_g_id = Column(Integer, primary_key=True, autoincrement=True)
    cfs = Column(String(5), default=None)
    type = Column(String(10), default=None)
    gstin = Column(String(50), default=None)
    invoice_date = Column(Date, default=None)
    invoice_number = Column(String(40), default=None)
    state  = Column(Integer,default=0)
    reverse_charge = Column(String(5), default=None)
    taxable_rate = Column(DECIMAL(6,2), default=None)
    taxable_value = Column(DECIMAL(15,2), default=None)
    iamt = Column(DECIMAL(15,2), default=None)
    camt = Column(DECIMAL(15,2), default=None)
    samt = Column(DECIMAL(15,2), default=None)
    csamt = Column(DECIMAL(15,2), default=None)
    elg = Column(String(10), default=None)
    tx_i = Column(DECIMAL(15,2), default=None)
    tx_c = Column(DECIMAL(15,2), default=None)
    tx_s = Column(DECIMAL(15,2), default=None)
    tx_cs = Column(DECIMAL(15,2), default=None)
    refund_number = Column(String(40), default=None)
    refund_date = Column(Date, default=None)
    reason  = Column(Text, nullable=False)
    document_type = Column(String(5), default=None)
    p_gst = Column(String(5), default=None)
    chksum  = Column(Text, nullable=False)
    flag = Column(String(5), default=None)
    cflag = Column(String(5), default=None)
    inv_typ = Column(String(5), default=None)
    new_entry  = Column(Integer,default=0)
    gstr_description  = Column(Text, nullable=False)
    amd_invoice_number = Column(String(30), default=None)
    amd_invoice_date = Column(Date, default=None)
    tax_period  = Column(DateTime, nullable=True)
    entry_date  = Column(DateTime, nullable=True) 

class  saleMaster(caerp_base):
    __tablename__ = 'sales_master'
    id = Column(Integer, primary_key=True, autoincrement=True)
    voucher_id = Column(Integer, nullable=False)
    head_id = Column(Integer, nullable=False)
    sub_head_id = Column(Integer, nullable=False)
    invoice_number = Column(String(20), nullable=False)
    invoice_date = Column(Date, nullable=False)
    financial_year_id = Column(Integer, nullable=False)
    tax_period = Column(Date, nullable=False)
    invoice_type = Column(Enum('B2B', 'B2C'), nullable=False, default='B2C')
    is_amended_invoice = Column(Integer, nullable=False, default=0)
    amended_invoice_number = Column(String(20), nullable=False)
    amended_invoice_date = Column(Date, nullable=True)
    amended_tax_period = Column(Date, nullable=True)
    has_gst_filed = Column(Enum('yes', 'no'), nullable=False, default='no')
    gst_filed_date = Column(DateTime, default=None)
    transportation_mode = Column(Integer, nullable=False)
    transported_date = Column(DateTime, default=None)
    vehicle_number = Column(String(50), default=None)
    port_code = Column(String(20), default=None)
    eway_bill_number = Column(String(16), nullable=False)
    payment_mode = Column(Enum('CASH', 'ONLINE', 'CREDIT'), nullable=False, default='CASH')
    transation_id = Column(String(50), default=None)
    discount_amount = Column(DECIMAL(15, 2), nullable=False)
    taxable_amount = Column(DECIMAL(15, 2), nullable=False)
    cgst_amount = Column(DECIMAL(15, 2), nullable=False)
    sgst_amount = Column(DECIMAL(15, 2), nullable=False)
    igst_amount = Column(DECIMAL(15, 2), nullable=False)
    cess_amount = Column(DECIMAL(15, 2), nullable=False)
    total_amount = Column(DECIMAL(15, 2), nullable=False)
    state_type = Column(Integer, nullable=False)
    b2c_state = Column(Integer, nullable=False)
    reverse_charge = Column(Enum('yes', 'no'), nullable=False, default='no')
    narration = Column(String(500), default=None)
    created_by = Column(Integer, nullable=False, default=0)
    created_on = Column(DateTime, nullable=False, default=func.now())
    modified_by = Column(Integer, default=None)
    modified_on = Column(DateTime, default=None)
    is_verified = Column(Enum('yes', 'no'), nullable=False, default='no')
    verified_by = Column(Integer, default=None)
    is_cancelled = Column(Enum('yes', 'no'), nullable=False, default='no')
    cancelled_by = Column(Integer, default=None)
    cancellation_reason = Column(String(100), default=None)
    is_deleted = Column(Enum('yes', 'no'), nullable=False, default='no')
    deleted_by = Column(Integer, default=None)
    deleted_on = Column(DateTime, default=None)

class  saleDetail(caerp_base):
    __tablename__ = 'sales_details'
    id = Column(Integer, primary_key=True, autoincrement=True)
    sales_master_id = Column(Integer, nullable=False)
    item_master_id = Column(Integer, nullable=False)
    hsn_sac_code = Column(String(20), nullable=False)
    gst_rate = Column(DECIMAL(7, 2), nullable=False)
    quantity = Column(DECIMAL(15, 2), nullable=False)
    sku_code = Column(String(50), default=None)
    unit_rate = Column(DECIMAL(15, 2), nullable=False)
    gross_amount = Column(DECIMAL(15, 2), nullable=False)
    discount_percentage = Column(DECIMAL(6, 2), nullable=False)
    discount_amount = Column(DECIMAL(15, 2), nullable=False)
    taxable_amount = Column(DECIMAL(15, 2), nullable=False)
    cgst_percentage = Column(DECIMAL(6, 2), nullable=False)
    cgst_amount = Column(DECIMAL(15, 2), nullable=False)
    sgst_percentage = Column(DECIMAL(6, 2), nullable=False)
    sgst_amount = Column(DECIMAL(15, 2), nullable=False)
    igst_percentage = Column(DECIMAL(6, 2), nullable=False)
    igst_amount = Column(DECIMAL(15, 2), nullable=False)
    cess_percentage = Column(DECIMAL(6, 2), nullable=False)
    cess_amount = Column(DECIMAL(15, 2), nullable=False)
    total_amount = Column(DECIMAL(15, 2), nullable=False)
    modified_by = Column(Integer, default=None)
    modified_on = Column(DateTime, default=None)
    is_deleted = Column(Enum('yes', 'no'), nullable=False, default='no')
    deleted_by = Column(Integer, default=None)
    deleted_on = Column(DateTime, default=None)

class  itemMaster(caerp_base):
    __tablename__ = 'item_master'
    item_id = Column(Integer, primary_key=True, autoincrement=True)
    item_name = Column(String(100), nullable=False)
    item_type = Column(Enum('GOODS', 'SERVICE'), nullable=False, default='GOODS')
    item_hsn_sac = Column(String(20), nullable=False)
    item_gst_tax = Column(DECIMAL(5, 2), nullable=False)
    item_sku = Column(String(20), nullable=False)
    item_selling_price = Column(DECIMAL(15, 2), nullable=False)
    item_purchase_price = Column(DECIMAL(15, 2), nullable=False)
    item_discount_percent = Column(Integer, nullable=False, default=0)
    item_cess_percent = Column(Integer, nullable=False, default=0)
    item_note = Column(String(100), nullable=False)
    itc_enable = Column(Enum('yes', 'no'), nullable=False, default='yes')
    opening_qty = Column(DECIMAL(15, 2), default=0)
    start_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=False)
    entry_date = Column(DateTime, nullable=False)

class  accountHead(caerp_base):
    __tablename__ = 'acc_account_head'
    account_head_id = Column(Integer, primary_key=True, autoincrement=True)
    account_group_id = Column(Integer, nullable=False)
    parent_head_id = Column(Integer, nullable=False)
    account_head_name = Column(String(100), nullable=False)
    account_head_alternate_name = Column(String(100), default=None)
    gstin = Column(String(20), default=None)
    is_default = Column(Integer, nullable=False, default=0)
    description = Column(String(100), default=None)
    is_deleted = Column(Integer, nullable=False, default=0)
