from enum import Enum
from pydantic import BaseModel
from typing import List,Optional, Union,Dict
from datetime import date, datetime
from caerp_constants.caerp_constants import BooleanFlag

class gstTestSchema(BaseModel):
   id   :   Optional[int]
   name :  Optional[str]
   gst  : Optional[str]
   amount :  Optional[float]


class gst2bSchema(BaseModel):
    p_g_id : Optional[int]
    cfs : Optional[str]
    type : Optional[str]
    supplier_name : Optional[str]
    supplier_tax_period: Optional[date]
    supplier_file_date: Optional[date]
    gstin  : Optional[str]
    invoice_date: Optional[date]
    invoice_number : Optional[str]
    applicable_tax_per : Optional[float]
    state : Optional[int]
    reverse_charge : Optional[str]
    taxable_rate : Optional[float]
    taxable_value : Optional[float]
    iamt : Optional[float]
    camt : Optional[float]
    samt : Optional[float]
    csamt : Optional[float]
    elg  : Optional[str]
    tx_i : Optional[float]
    tx_c : Optional[float]
    tx_s : Optional[float]
    tx_cs : Optional[float]
    refund_number : Optional[str]
    refund_date: Optional[date]
    reason : Optional[str]
    document_type : Optional[str]
    p_gst : Optional[str]
    chksum : Optional[str]
    flag : Optional[str]
    cflag : Optional[str]
    inv_typ : Optional[str]
    new_entry : Optional[int]
    gstr_description : Optional[str]
    amd_invoice_number : Optional[str]
    amd_invoice_date: Optional[date]
    tax_period  : Optional[datetime] = None
    entry_date  : Optional[datetime] = None


class gst2aSchema(BaseModel):
   p_g_id  : Optional[int]
   cfs : Optional[str]
   type : Optional[str]
   gstin : Optional[str]
   invoice_date : Optional[date]
   invoice_number : Optional[str]
   state  : Optional[int]
   reverse_charge : Optional[str]
   taxable_rate : Optional[float]
   taxable_value : Optional[float]
   iamt : Optional[float]
   camt : Optional[float]
   samt : Optional[float]
   csamt : Optional[float]
   elg : Optional[str]
   tx_i : Optional[float]
   tx_c : Optional[float]
   tx_s : Optional[float]
   tx_cs : Optional[float]
   refund_number : Optional[str]
   refund_date : Optional[date]
   reason  : Optional[str]
   document_type : Optional[str]
   p_gst : Optional[str]
   chksum  : Optional[str]
   flag : Optional[str]
   cflag : Optional[str]
   inv_typ : Optional[str]
   new_entry  : Optional[int]
   gstr_description  : Optional[str]
   amd_invoice_number : Optional[str]
   amd_invoice_date : Optional[date]
   tax_period  : Optional[datetime] = None
   entry_date  : Optional[datetime] = None 

class YesNoEnum(str, Enum):
    yes = 'yes'
    no = 'no'

class InvoiceTypeEnum(str, Enum):
    B2B = 'B2B'
    B2C = 'B2C'

class PurchaseInvoiceTypeEnum(str, Enum):
    B2B = 'B2B'
    B2BUR = 'B2BUR'
class paymentEnum(str, Enum):
    CASH = 'CASH'
    ONLINE = 'ONLINE'
    CREDIT = 'CREDIT'

class noteTypeEnum(str, Enum):
    CREDIT = 'CREDIT'
    DEBIT = 'DEBIT'
    REVISE = 'REVISE'

class purchaseTypeEnum(str, Enum):
    normal = 'normal'
    expense = 'expense'

class unregisteredEnum(str, Enum): 
    B2CL = 'B2CL'
    EXPWP = 'EXPWP'
    EXPWOP = 'EXPWOP'
class saleMasterSchema(BaseModel):
    id:Optional[int]
    voucher_id:Optional[int]
    head_id:Optional[int]
    sub_head_id:Optional[int]
    invoice_number:Optional[str]
    invoice_date:Optional[date]
    financial_year_id:Optional[int]
    tax_period:Optional[date]
    invoice_type:Optional[InvoiceTypeEnum]
    is_amended_invoice:Optional[int]
    amended_invoice_number:Optional[str]
    amended_invoice_date:Optional[date]
    amended_tax_period:Optional[date]
    has_gst_filed:Optional[YesNoEnum]
    gst_filed_date:Optional[datetime]
    transportation_mode:Optional[int]
    transported_date:Optional[datetime]
    vehicle_number:Optional[str]
    port_code:Optional[str]
    eway_bill_number:Optional[str]
    payment_mode:Optional[paymentEnum]
    transation_id:Optional[str]
    gross_total:Optional[float]
    discount_amount:Optional[float]
    taxable_amount:Optional[float]
    cgst_amount:Optional[float]
    sgst_amount:Optional[float]
    igst_amount:Optional[float]
    cess_amount:Optional[float]
    total_amount:Optional[float]
    state_type:Optional[int]
    b2c_state:Optional[int]
    reverse_charge:Optional[YesNoEnum]
    narration:Optional[str]
    created_by:Optional[int]
    created_on:Optional[datetime]
    modified_by:Optional[int]
    modified_on:Optional[datetime]
    is_verified:Optional[YesNoEnum]
    verified_by:Optional[int]
    is_cancelled:Optional[YesNoEnum]
    cancelled_by:Optional[int]
    cancellation_reason:Optional[str]
    is_deleted:Optional[YesNoEnum]
    deleted_by:Optional[int]
    deleted_on:Optional[datetime]


class saleDetailsSchema(BaseModel):
    id:Optional[int]
    sales_master_id:Optional[int]
    item_master_id:Optional[int]
    hsn_sac_code:Optional[str]
    gst_rate:Optional[float]
    quantity:Optional[float]
    sku_code:Optional[str]
    unit_rate:Optional[float]
    gross_amount:Optional[float]
    discount_percentage:Optional[float]
    discount_amount:Optional[float]
    taxable_amount:Optional[float]
    cgst_percentage:Optional[float]
    cgst_amount:Optional[float]
    sgst_percentage:Optional[float]
    sgst_amount:Optional[float]
    igst_percentage:Optional[float]
    igst_amount:Optional[float]
    cess_percentage:Optional[float]
    cess_amount:Optional[float]
    total_amount:Optional[float]
    modified_by:Optional[int]
    modified_on:Optional[datetime]
    is_deleted:Optional[YesNoEnum]
    deleted_by:Optional[int]
    deleted_on:Optional[datetime]

class itemMasterSchema(BaseModel):
    item_id:Optional[int]
    item_name:Optional[str]
    item_type:Optional[str]
    item_hsn_sac:Optional[str]
    item_gst_tax:Optional[float]
    item_sku:Optional[str]
    item_selling_price:Optional[float]
    item_purchase_price:Optional[float]
    item_discount_percent:Optional[int]
    item_cess_percent:Optional[int]
    item_note:Optional[str]
    itc_enable:Optional[YesNoEnum]
    opening_qty:Optional[float]
    start_date:Optional[date]
    end_date:Optional[date]
    entry_date:Optional[datetime]

class accountHeadSchema(BaseModel):
    account_head_id:Optional[int]
    account_group_id:Optional[int]
    parent_head_id:Optional[int]
    account_head_name:Optional[str]
    account_head_alternate_name:Optional[str]
    gstin:Optional[str]
    is_default:Optional[int]
    description:Optional[str]
    is_deleted:Optional[int]

class purchaseMasterSchema(BaseModel):
    id:Optional[int]
    voucher_id:Optional[int]
    head_id:Optional[int]
    sub_head_id:Optional[int]
    invoice_number:Optional[str]
    invoice_date:Optional[date]
    financial_year_id:Optional[int]
    tax_period:Optional[date]
    invoice_type:Optional[PurchaseInvoiceTypeEnum]
    is_amended_invoice:Optional[int]
    amended_invoice_number:Optional[str]
    amended_invoice_date:Optional[date]
    amended_tax_period:Optional[date]
    has_gst_filed:Optional[YesNoEnum]
    gst_filed_date:Optional[datetime]
    transportation_mode:Optional[int]
    transported_date:Optional[datetime]
    vehicle_number:Optional[str]
    port_code:Optional[str]
    eway_bill_number:Optional[str]
    payment_mode:Optional[paymentEnum]
    transation_id:Optional[str]
    gross_total:Optional[float]
    discount_amount:Optional[float]
    taxable_amount:Optional[float]
    cgst_amount:Optional[float]
    sgst_amount:Optional[float]
    igst_amount:Optional[float]
    cess_amount:Optional[float]
    round_off_amount:Optional[float]
    total_amount:Optional[float]
    state_type:Optional[int]
    b2c_state:Optional[int]
    reverse_charge:Optional[YesNoEnum]
    is_composite:Optional[YesNoEnum]
    narration:Optional[str]
    created_by:Optional[int]
    created_on:Optional[datetime]
    modified_by:Optional[int]
    modified_on:Optional[datetime]
    is_verified:Optional[int]
    verified_by:Optional[int]
    is_cancelled:Optional[int]
    cancelled_by:Optional[int]
    cancellation_reason:Optional[str]
    is_deleted:Optional[int]
    deleted_by:Optional[int]
    deleted_on:Optional[datetime]

class purchaseDetailSchema(BaseModel):
    id:Optional[int]
    purchase_master_id:Optional[int]
    item_master_id:Optional[int]
    purchase_type:Optional[purchaseTypeEnum]
    itc_type:Optional[YesNoEnum]
    hsn_sac_code:Optional[str]
    gst_rate:Optional[float]
    quantity:Optional[float]
    sku_code:Optional[str]
    unit_rate:Optional[float]
    gross_amount:Optional[float]
    discount_percentage:Optional[float]
    discount_amount:Optional[float]
    taxable_amount:Optional[float]
    cgst_percentage:Optional[float]
    cgst_amount:Optional[float]
    sgst_percentage:Optional[float]
    sgst_amount:Optional[float]
    igst_percentage:Optional[float]
    igst_amount:Optional[float]
    cess_percentage:Optional[float]
    cess_amount:Optional[float]
    total_amount:Optional[float]
    modified_by:Optional[int]
    modified_on:Optional[datetime]
    is_deleted:Optional[int]
    deleted_by:Optional[int]
    deleted_on:Optional[datetime]

class creditMasterSchema(BaseModel):
    id:Optional[int]
    voucher_id:Optional[int]
    head_id:Optional[int]
    sub_head_id:Optional[int]
    note_number:Optional[str]
    note_date:Optional[date]
    financial_year_id:Optional[int]
    tax_period:Optional[date]
    note_type:Optional[noteTypeEnum]
    reason_for_issue:Optional[str]
    is_amended_credit_note:Optional[int]
    amended_note_number:Optional[str]
    amended_note_date:Optional[date]
    amended_tax_period:Optional[date]
    has_gst_filed:Optional[YesNoEnum]
    gst_filed_date:Optional[datetime]
    transportation_mode:Optional[int]
    transported_date:Optional[datetime]
    vehicle_number:Optional[str]
    port_code:Optional[str]
    eway_bill_number:Optional[str]
    payment_mode:Optional[paymentEnum]
    transation_id:Optional[str]   
    discount_amount:Optional[float]
    taxable_amount:Optional[float]    
    cgst_amount:Optional[float]
    sgst_amount:Optional[float]
    igst_amount:Optional[float]
    cess_amount:Optional[float]
    total_amount:Optional[float]
    state_type:Optional[int]
    b2c_state:Optional[int]
    registered:Optional[YesNoEnum]
    unregistered_type:Optional[unregisteredEnum] 
    narration:Optional[str]
    created_by:Optional[int]
    created_on:Optional[datetime]    
    modified_by:Optional[int]
    modified_on:Optional[datetime]
    is_verified:Optional[YesNoEnum]
    verified_by:Optional[int]
    is_cancelled:Optional[YesNoEnum]
    cancelled_by:Optional[int]
    cancellation_reason:Optional[str]
    is_deleted:Optional[YesNoEnum]
    deleted_by:Optional[int]
    deleted_on:Optional[datetime]

class creditDetailSchema(BaseModel):
    id:Optional[int]
    credit_note_master_id:Optional[int]
    item_master_id:Optional[int]
    hsn_sac_code:Optional[str]
    gst_rate:Optional[float]
    quantity:Optional[float]
    sku_code:Optional[str]
    unit_rate:Optional[float]
    gross_amount:Optional[float]
    discount_percentage:Optional[float]
    discount_amount:Optional[float]
    taxable_amount:Optional[float]
    cgst_percentage:Optional[float]
    cgst_amount:Optional[float]
    sgst_percentage:Optional[float]    
    sgst_amount:Optional[float]
    igst_percentage:Optional[float]    
    igst_amount:Optional[float]
    cess_percentage:Optional[float]    
    cess_amount:Optional[float]
    total_amount:Optional[float]
    modified_by:Optional[int]
    modified_on:Optional[datetime]
    is_deleted:Optional[YesNoEnum]
    deleted_by:Optional[int]
    deleted_on:Optional[datetime]
